### ISSUE TITLE
Authentication with seamless R

### ISSUE THREAD

**Issue by DnPeter** [itsdalmo/officeR#2]
You have a example to SharePoint Authentication with seamless and httr?

Thanks

DC

**Comment by itsdalmo** [comment]
Hi,

Sorry, there is just the one example which is in the [documentation](https://github.com/itsdalmo/seamless/blob/master/R/sharepoint.R#L19-L21) for the function, which was meant for internal use in my old job.

I did not make a more general implementation because some (old) sharepoint servers use SOAP, newer ones use REST, and additionally, the authentication method might differ between servers. 

If you need access to sharepoint I'd suggest looking at the code in sharepoint.R, and adjust it to your needs :)
